### ISSUE TITLE
how to override POS tag

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-recursive#19]
I'm trying to override the POS tag manually.

An example rule:

```
      8: бар@AP %vP.cop [$barjoq=barjoq] { %*(vblex)[lemh=have] } |
```

Here we [correctly] end up with `have@vP.everything.else` instead of `have@vblex.everything.else`.  The issue is how to override `vP` with `vblex`.  I could force it with an attribute that applies to both of those, but I think there should be an equivalent of `lemh` for first tag?  @mr-martian, do you know if it exists / what it is?

**Comment by mr-martian** [comment]
Are you saying this generates `have<vP><whatever>` in the output and you want `have<vblex><whatever>`? If so, do `[lemh=have, pos_tag=vblex]`.

**Comment by jonorthwash** [comment]
Yes, exactly.  `pos_tag` is what I was looking for.  Though I ended up hacking this the old-fashioned way: `бар@AP %vP.cop [$barjoq=barjoq] { have@vblex.$tense.$person.$number }`.  I wonder which is preferred?

**Comment by jonorthwash** [comment]
Btw, the documentation doesn't really define `lem(h)` or `pos_tag`.  Maybe there should be a list of "reserved words" or similar?

**Comment by jonorthwash** [comment]
@mr-martian, another question about this rule: how do I get `$number` to propagate from the `VP` rule above it?

**Comment by mr-martian** [comment]
@jonorthwash `%` wasn't supposed to override `pos_tag`, because the value of `pos_tag` would be assumed to be `<vblex>`. (I have fixed this)

I think the preferred pattern would probably be `%have(vblex)`, since that way you can handle capitalization if you need to and can rely on the verb macros to get the right tags.

As for the question about number, I think the answer is yes, but I'm not sure I understand the question.

**Comment by jonorthwash** [comment]
Could you pull `apertium-eng-kir` and try "Мышыктардын үйү бар." ("The cats have a house.") in reference to the rule on line 358?  I can't seem to get the verb to be `<pl>` based on the `DP` subject.

**Comment by mr-martian** [comment]
The `VP` isn't getting `<pl>` there because `S` doesn't have a number tag, so `$number` is `""`. What you want is `[number=1.number]`, which I just pushed.

**Comment by jonorthwash** [comment]
> What you want is `[number=1.number]`,

Ohhh....  I figured I was missing something silly like that.

> which I just pushed.

Thanks!  Tested and works!
