### ISSUE TITLE
infinite loops on деп-related sentences

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-recursive#21]
If you have a sentence like "Мен досум барам деп айттым." in a larger file, `rtx-proc` loops infinitely.

**Comment by mr-martian** [comment]
@jonorthwash assuming such a sentence occurs in `texts/story.kir.txt`, the issue is actually with `lrx-proc` and appears to be a memory leak.

**Comment by mr-martian** [comment]
Issue transferred to https://github.com/apertium/apertium-lex-tools/issues/29
