### ISSUE TITLE
numbers get repeated?

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-recursive#22]
@mr-martian, I'm having a weird issue.  Currently the following sentence
```
Ал 17-кылымда төрөлгөн.
```
translates as
```
He was borne in the 1717th century.
```
Do you have any idea why we get the number doubled?

**Comment by mr-martian** [comment]
kir-eng.rtx line 129:
```
adj_ord: lemh.<adj>.<ord> ;
```
`lemh` is automatically prefixed to the pattern, so explicitly mentioning it is what causes the doubling.

**Comment by jonorthwash** [comment]
Aha, good to know.  I seem to remember `_` meaning "lemma and first tag"—did that change or am I misremembering?

**Comment by mr-martian** [comment]
It did. At some point I made it just first tag on the assumption that there should always be a lemma and it should always be first.
