### ISSUE TITLE
features coming from /ref by default??

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-recursive#27]
I seem to be getting subject—possessed-object number agreement, apparently because of `/ref`?

In the sentence "Мышыктардын үйү бар.", for example, the second noun gets `<pl>` when only `/ref` has any indication of `pl`.

```
Applying rule 2 (line 218) to branch 2 with weight 1: ^үй<n><px3sp><nom>/house<n><px3sp><nom>/Cat<n><pl><gen>$

^үй<NP><n><pl><px3sp><nom><in><GD>{
	^үй<n><px3sp><nom>/house<n><px3sp><nom>/Cat<n><pl><gen>$
}$
```

The rule in question is the following:
```
NP ->	
      1: n.$nptype.$lem/sl.$case/sl.$number.$poss
         [$prep_flag=(if (1.lem in en_nouns_loc_in) in
                      else-if (1.lem in en_nouns_loc_on) on
                      else-if (1.lem in en_nouns_loc_at) at
                      else 1.case/sl>prep_flag
                     ),
          $REF_gender=1.gender/ref>REF_gender
         ] { 1[lemcase=$lemcase, number=$number] } |
```

**Comment by mr-martian** [comment]
`.$number`, since a side isn't specified, will clip from target, and if the value it gets is the `<ND>` or the empty string it will try again with reference, and if then with source. It's coming from `/ref` in this case because `/ref` is the only side with a number tag.

**Comment by jonorthwash** [comment]
Aha, that makes sense, and I guess it sounds like reasonable/desired behaviour.  Thanks; fixed that now!
