### ISSUE TITLE
Rules not being applied in all cases

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium-recursive#29]
Hello,

I am working on this set of rules: https://github.com/apertium/apertium-eng-cat/blob/recursive-eng-cat/apertium-eng-cat.eng-cat.rtx

Given the following input:
`^beautiful<adj>/bonic<adj>/$^,<cm>/,<cm>/$`

The output of rtx-proc is:
`^bonic<adj>$^,<cm>$`

However, given that there is a rule on line 107 for "adj", I would expect the output to be:
`^bonic<adj><m><sg>$^,<cm>$`

This rule (line 107) is applied correctly when only the first token is present.

Taking a look at the summary of the operations, it looks like the rule is recognised but then discarded for some reason:

```
Reading Input:
^beautiful<adj>/bonic<adj>$

Checking for reductions for branch 1

Applying rule 16 (line 107) to branch 1 with weight 0: ^beautiful<adj>/bonic<adj>$

^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$

Checking for reductions for branch 1
No further reductions possible for branch 1.

Splitting stack and creating branch 2
Branch 1: 1 nodes, weight = 0
[Chunk]:
^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$
Branch 2: 1 nodes, weight = 0
[Chunk]:
^beautiful<adj>/bonic<adj>$

Filtering Branches:
Branch 1  has no possible continuations.
Branch 2
Reading Input:
^,<cm>/,<cm>$

Checking for reductions for branch 2
No further reductions possible for branch 2.
Branch 2: 3 nodes, weight = 0
[Chunk]:
^beautiful<adj>/bonic<adj>$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$

Filtering Branches:
Input buffer is empty.
Branch 2  has no active branch to compare to.

************************************************************
************************************************************
************************************************************
Outputting Branch 2

[Chunk]:
^beautiful<adj>/bonic<adj>$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$
************************************************************
************************************************************
************************************************************

Output Node:
^beautiful<adj>/bonic<adj>$

^bonic<adj>$Output Node:
^,<cm>/,<cm>$

^,<cm>$
```

Is this behaviour correct? Am I missing something in my set of rules to handle this? Thanks!

**Comment by mr-martian** [comment]
So first the rule matches the adjective, and then it splits the stack because there are other rules that begin with adjectives. Then it reads the comma and the problem is that a rule beginning with "adj cm" exists on line 116, but nothing will ever match "SAdj cm", so it treats "SAdj cm" as a parse error and only holds on to "adj cm".

This behavior is correct in the sense that it's what I expect to happen, but fixing it would also be nice.

The workaround is to write a rule whose pattern begins with "SAdj cm", even if it's something intentionally useless like
```
FALLBACK: _;
NONEXISTENT: _;
FALLBACK -> SAdj cm NONEXISTENT ?(x = y) {} ;
```
which will make it give the output you were expecting.

**Comment by MarcRiera** [comment]
Thanks for the explanation. I will be using the workaround provisionally and hope that you will be able to fix this, it seems a little obscure after being used to the behaviour of apertium-transfer.

**Comment by MarcRiera** [comment]
I have been finally able to test your workaround (changing "SAdj" to "adj" on the third line, because the conflicting rule is "adj cm" and not "SAdj cm") but unfortunately the output is the same:

```
Reading Input:
^beautiful<adj>/bonic<adj>$

Checking for reductions for branch 1

Applying rule 16 (line 107) to branch 1 with weight 0: ^beautiful<adj>/bonic<adj>$

^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$

Checking for reductions for branch 1
No further reductions possible for branch 1.

Splitting stack and creating branch 2
Branch 1: 1 nodes, weight = 0
[Chunk]:
^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$
Branch 2: 1 nodes, weight = 0
[Chunk]:
^beautiful<adj>/bonic<adj>$

Filtering Branches:
Branch 1  has no possible continuations.
Branch 2
Reading Input:
^,<cm>/,<cm>$

Checking for reductions for branch 2
No further reductions possible for branch 2.
Branch 2: 3 nodes, weight = 0
[Chunk]:
^beautiful<adj>/bonic<adj>$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$

Filtering Branches:
Input buffer is empty.
Branch 2  has no active branch to compare to.

************************************************************
************************************************************
************************************************************
Outputting Branch 2

[Chunk]:
^beautiful<adj>/bonic<adj>$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$
************************************************************
************************************************************
************************************************************

Output Node:
^beautiful<adj>/bonic<adj>$

^bonic<adj>$Output Node:
^,<cm>/,<cm>$

^,<cm>$
```

**Comment by mr-martian** [comment]
The workaround actually depends on it being "Sadj". The problem is that that the parser has an internal state that looks like this:

```
Stack 1          Stack 2
<cm>             <cm>
<Sadj>           <adj>
```

And it's looking for rules that match the top of those stacks. There aren't any such rules, so it tries to determine whether any rules might match one of these if it read in more input. Stack 2 would match if it read another `<adj>`, but Stack 1 will never be matched, so it discards Stack 1. What the workaround does by making a rule for "Sadj cm NONEXISTENT" is make it think that there exists something which could match Stack 1.

**Comment by MarcRiera** [comment]
I see... I understand what you mean. Changed it back to what you first proposed (with "SAdj") and the output is the same, but something different is going on internally (now it does not mention that branch 1 has multiple continuations):

```
Reading Input:
^beautiful<adj>/bonic<adj>$

Checking for reductions for branch 1

Applying rule 16 (line 107) to branch 1 with weight 0: ^beautiful<adj>/bonic<adj>$

^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$

Checking for reductions for branch 1
No further reductions possible for branch 1.

Splitting stack and creating branch 2
Branch 1: 1 nodes, weight = 0
[Chunk]:
^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$
Branch 2: 1 nodes, weight = 0
[Chunk]:
^beautiful<adj>/bonic<adj>$

Filtering Branches:
Branch 1 Branch 2
Reading Input:
^,<cm>/,<cm>$

Checking for reductions for branch 1
No further reductions possible for branch 1.
Checking for reductions for branch 2
No further reductions possible for branch 2.
Branch 1: 3 nodes, weight = 0
[Chunk]:
^bonic<SAdj><GD><ND>{
        ^beautiful<adj>/bonic<adj>$
}$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$
Branch 2: 3 nodes, weight = 0
[Chunk]:
^beautiful<adj>/bonic<adj>$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$

Filtering Branches:
Input buffer is empty.
Branch 1  has no active branch to compare to.
Branch 2  has fewer partial parses or a higher weight than branch 1.

************************************************************
************************************************************
************************************************************
Outputting Branch 2

[Chunk]:
^beautiful<adj>/bonic<adj>$
[Blank]:
[Chunk]:
^,<cm>/,<cm>$
************************************************************
************************************************************
************************************************************

Output Node:
^beautiful<adj>/bonic<adj>$

^bonic<adj>$Output Node:
^,<cm>/,<cm>$

^,<cm>$
```

**Comment by mr-martian** [comment]
Now it's a weight issue. Try making your `SAdj -> adj` rule have `SAdj -> 1: adj`. It's getting to the end and both parses have the same weight and size so it has to choose somewhat arbitrarily.

**Comment by MarcRiera** [comment]
Temporarily "fixed" this for apertium-eng-cat here: https://github.com/apertium/apertium-eng-cat/commit/fd7807fcbd7ecc7c5f4540f1b0e63830af1df73a

Yesterday I discussed this with @xavivars (both in person and on the commit linked above) and we agree that the behaviour of apertium-recursive should match that of other modules and default to applying rules with shorter patterns instead of doing nothing and having to use workarounds like this one. Currently it is only two rules, but it has the potential of requiring many more as the number of rules grows and requiring more effort.

Thanks!

**Comment by mr-martian** [comment]
I still have no idea how to fix this in general, but it occurs to me that a better workaround might be to have your `SAdj -> adj cm adj` rule be `SAdj -> SAdj cm SAdj` which would entirely avoid the necessity of `FALLBACK`.

**Comment by mr-martian** [comment]
I suspect the solution to this bug will be some variation of internally generating fallback rules like the ones discussed above. However, I don't have a clear idea how to programmatically detect cases where such rules will be needed.

**Comment by jonorthwash** [comment]
I've been getting a similar with lemmas joined with `+` in `lsx-proc`.  I should probably file a bug there...

```
$ echo "бүгүнкү күндө" | apertium -d . kir-eng
he is on the today day

$ echo "бүгүнкү күндө түшөт" | apertium -d . kir-eng
he falls these days
```

**Comment by mr-martian** [comment]
@jonorthwash What are these sentences supposed to be? Also any `+`s will get removed by apertium-pretransfer.

**Comment by jonorthwash** [comment]
Filed here: https://github.com/apertium/apertium-separable/issues/13

**Comment by mr-martian** [comment]
I think the solution is probably as follows:

Look for any pair of rules
```
X -> A*
Y -> A* B C*
```
Such that neither of the following exist:
```
Z -> X B
Z -> X B D*
```
Then add to the pattern transducer the path `X B [blank]`.

**Comment by mr-martian** [comment]
@MarcRiera This fixes it for me. Could you check that it works for your instance?

**Comment by MarcRiera** [comment]
Yes, I have removed the fallback rules and the behaviour is now correct. Thank you for your hard work looking into this!
