### ISSUE TITLE
Match unknown words

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium-recursive#30]
Some t1x rules match unknown words with
```xml
    <def-cat n="unknown">
      <cat-item tags=""/>
    </def-cat>
```
Perhaps `*` in the pattern for rtx should do the same?

We would have to make sure this doesn't conflict with the current implementation of lookahead.

**Comment by mr-martian** [comment]
One solution would be to have a special rule that matches `^\*<ANY_CHAR>*$` and converts it to `^lem<UNKNOWN>{^*lem/*lem$}$` so that other rules can simply match `UNKNOWN` without fear of it messing up lookahead.

**Comment by mr-martian** [comment]
At read time, `^*lem/*lem$` is now automatically converted to `^lem<UNKNOWN:INTERNAL>{^*lem/*lem$}$`. The choice of tag should mostly prevent conflicts with user tags.

**Comment by unhammer** [comment]
To anyone trying to use this in an rtx file, the `:` must be escaped like `\:`

Example added at https://wiki.apertium.org/wiki/Apertium-recursive/Formalism#Matching_unknowns

**Comment by mr-martian** [comment]
There's actually an undocumented shortcut, which is to put the part of speech as `*`. I've updated the wiki page.
