### ISSUE TITLE
Unable to properly conjoin LUs

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium-recursive#32]
### Sample rule file
```
prn: _.prn_type.person.gender.number ;
vblex: _.tense;
Clt: _.prn_type.person.gender.number ;
SV: _.vb_type.vb_cnj.tense.person.gender.number ;

gender = (GD m) m f nt @mf GD ;
number = (ND sg) sg pl @sp ND ;
person = (PD p3) p1 p2 p3 PD ;
prn_type = tn itg pro enc ;
tense = pri fti cni imp prs pis fts pii ifi inf ger pp ;
vb_type = vbhaver vblex vbmod vbser ;
vb_cnj = cnj impers ;

Clt ->  1: %prn.enc
                { %1 } ;

SV ->   2: %vblex.inf
                [$vb_cnj=impers]
                { (if($lu-count="2") [%1+>2] else %1 ) } |

        2: %SV.*.impers.inf Clt.enc
                { %1 < 2 } ;
```
### Input
```
^cantar<vblex><inf>/cantar<vblex><inf>$ ^nos<prn><enc><p1><mf><pl>/ens<prn><enc><p1><mf><pl>$
```
### Output
```
^cantar<vblex><inf>ens<Clt><enc><p1><mf><pl>$
```
### Expected output
```
^cantar<vblex><inf>+ens<prn><enc><p1><mf><pl>$ 
```
### Description
There are 2 aspects not working as I would expect, all related to the third rule:
1. `+` is missing in the output between the conjoined parts.

2. The second part of the rule is output as the lemma and tags of the chunk created in the first (Clt) rule and not the content, that is, the content inside the chunk is completely ignored.

Thanks!

**Comment by mr-martian** [comment]
I think probably the best way to fix both this and #7 is to move handling of `+` from the rule application to the output step so that `+` adds an instruction to the output queue to conjoin whatever's on either side of it. Then `+` will always conjoin surface forms.

The lack of a literal `+` in the output is probably an actual bug.

**Comment by mr-martian** [comment]
@MarcRiera It works for me now, and you could even simplify it to
```
SV ->   2: %vblex.inf
                [$vb_cnj=impers]
                { %1 } |

        2: %SV.*.impers.inf Clt.enc
                { %1 + 2 } ;
```

**Comment by MarcRiera** [comment]
It does work, thank you!
