### ISSUE TITLE
Lemmas with queues cannot be properly conjoined

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium-recursive#38]
Currently it does not seem possible to properly conjoin lemmas when the first one has a queue. This is very common with verbs and clitics and can be done easily in ```apertium-transfer```, which allows to specify the clipping position of ```lemh``` and ```lemq```. Example with a verb and a clitic:

**Source**
```
^tenir# en compte<vblex><ger>$ ^ho<prn><enc><p3><nt>$
```

**Current output**
```
^tenir<vblex><ger># en compte+ho<prn><enc><p3><nt>$
```

**Expected output**
```
^tenir<vblex><ger>+ho<prn><enc><p3><nt># en compte$
```
For lemmas that are not yet inside of a chunk, it seems straightforward. However, given that it is also possible to conjoin whole chunks, I am not entirely sure how this would be handled.

**Comment by mr-martian** [comment]
This would be a case of me not attempting to deal with it correctly, having never actually seen much use of `lemq`.

I can try to think of a way to handle this, but I suspect the simplest would be to pass `lemq` up the tree and if there's a place where something is conjoined, delete the `lemq` from the verb and attach it to the clitic.

**Comment by mr-martian** [comment]
@MarcRiera see if 7127ba3 does what you want.

Is there ever a case where you want to combine things that both have lemqs? What I just implemented would turn `A# X + B# Y` into `A+B# Y# X`, which seems quite possibly wrong, but also unlikely to come up (especially as this starts being done more with -separable).

**Comment by MarcRiera** [comment]
It does exactly what I was expecting, thanks!

I cannot think right now of a case where two units with lemqs would be combined, it is not something I have in the pairs I work on. In any case, the current implementation seems correct, as it would generate properly after transfer. I'm closing the issue as solved.
