### ISSUE TITLE
Don't output a blank if an LU is empty

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-recursive#42]
Sometimes we want to do things like:

```
      <out>
       <chunk name="SV">
        <tags>
         <tag><lit-tag v="SV"/></tag>
          <tag><clip pos="1" side="tl" part="a_val"/></tag>
        </tags>
        <var n="CI"/> <b/>
        <lu> <clip pos="1" side="tl" part="whole"/> </lu>
       </chunk>
      </out>
```

But if the variable is empty, the blank still gets output, which means that we get two spaces instead of one. If the variable is empty, the blank should not be output.... I can't think of any counter example to this.

**Comment by mr-martian** [comment]
What if I allowed conditionals inside `<out>`? Then your example could be written as follows:
```xml
<out>
  <chunk name="SV">
    <tags>
      <tag><lit-tag v="SV"/></tag>
      <tag><clip pos="1" side="tl" part="a_val"/></tag>
    </tags>
    <choose>
      <when>
        <test><not><equal><var n="CI"/><lit v=""/></equal></not></test>
        <lu><var n="CI"/></lu>
        <b/>
      </when>
    </choose>
    <lu> <clip pos="1" side="tl" part="whole"/> </lu>
  </chunk>
</out>
```
Would that be a satisfactory solution?

Alternatively, what about `<lu from="CI" blank-after="yes"/>`? (`blank-after="yes"` being "insert a `<b/>` after this if it's non-empty")

**Comment by ftyers** [comment]
Actually with `apertium-posttransfer` this isn't really necessary any more. 

I don't like the idea of having conditionals in the output section, but the `blank-after` idea is not bad. But I'd make it default to yes and have a `blank-after="no"` to turn it off. 

Also, the whole "insert blank if non-empty" is basically how it should function anyway. Right?

**Comment by ftyers** [comment]
Going to close this as `-postransfer solves it`.
