### ISSUE TITLE
Automatic resolving of linked properties

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-recursive#43]
Sometimes you want to be able to link stuff to a chunk tag, but the exact position of the tag is uncertain because there may or may not be intervening tags. e.g. if you have 
`^SN<px3sg><m><sg>$` and `^SN<m><sg>$`, you may want to do,
```
        <lu><clip pos="1" side="tl" part="a_gen" link-to="3"/></lu>
```
But that would have to be `2` in the case of the second example. Usually tags in a chunk are not ambiguous, so would it be possible to do something like,
```
<lu><clip pos="1" side="tl" part="a_gen" link/></lu>
```
And have it automatically resolve? e.g. pull out the part of the chunk that corresponds to `a_gen`?

**Comment by mr-martian** [comment]
I think the way to do this would be for each attribute to have a specific placeholder tag (`<rtx:a_gen>`, maybe?) and then have the postchunk rules check for them and replace them.

**Comment by ftyers** [comment]
Another idea, 

```
  <rule comment="SN" firstChunk="SN">
   <pattern>
    <pattern-item n="N"/>
   </pattern>
   <action>
      <call-macro n="f_set_chunk_name1"><with-param pos="1"/></call-macro>
      <out>
       <chunk namefrom="chunkName">
        <tags>
         <tag><lit-tag v="SN"/></tag>
         <tag><clip pos="1" side="tl" part="a_poss"/></tag>
         <tag n="gen"><clip pos="1" side="tl" part="a_gen"/></tag>
         <tag><clip pos="1" side="tl" part="a_nbr"/></tag>
        </tags>
        <link-to><tag v="gen"/><clip pos="1" side="tl" part="a_gen"/></link-to>
        <lu><clip pos="1" side="tl" part="whole"/></lu>
       </chunk>
      </out>
   </action>
  </rule>
```

Semantics:
`<tag n="gen"><clip pos="1" side="tl" part="a_gen"/></tag>`

Define a chunk tag with the label `gen` and fill it with the contents of `<clip pos="1" side="tl" part="a_gen"/>`

`<link-to><tag v="gen"/><clip pos="1" side="tl" part="a_gen"/></link-to>`

Replace the `tl` part of the LU that matches `a_gen` with a link to `gen`.

`<lu><clip pos="1" side="tl" part="whole"/></lu>`

Define the LU.

I don't like the idea of using the `<...:...>` approach. Is there a way to do this without that?

**Comment by ftyers** [comment]
I'm pretty happy with how things are working at the moment, I think that a reasonable approach is to statically define linked variables at the beginning and then just concatenate things that are not linked to the end. We can potentially close this for now, but leave it with the idea tag for the future in case it needs to be reopened.
