### ISSUE TITLE
Compile .t*x Files

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium-recursive#5]
- [x] I ensured that all rules have separate paths, but this prevents checking for conflicts.
- [x] Some words occasionally lose tags, particularly ```<ger>``` and ```<prn>```
- [x] A few empty chunks are produced

See also #3

**Comment by mr-martian** [comment]
Unanswered questions relevant to compilation:

- ```<transfer default="chunk">``` vs ```<transfer default="lu">```
- update the output rule if we change the lemma of a chunk
- The DTD seems to imply that macros can take variable numbers of arguments
- The DTD says that ```<append>``` can modify clips
- What does the ```queue``` attribute on clips do?
- ```<mlu>``` in the chunker has a check against producing ```++``` and ```+#```
- I implemented ```<chunk>``` with both ```name``` and ```namefrom``` being empty as having the lemma ```"default"```
- ```<clip>``` inside ```<chunk>``` could use more error checking

**Comment by mr-martian** [comment]
As it turns out, the VM makes some assumptions which existing rules occasionally violate:

- The input stream to a rule is always an alternating string of chunks/LUs and blanks
- Any particular string will contain at most one chunk

I can deal with some of this in the compiler, but other things have required adding complications to the VM which seems to largely negate the speed benefits of compiling to bytecode.

**Comment by unhammer** [comment]
Which compiler is that? (There's the standard one, the vm-for-transfer ones and the java one..)

**Comment by mr-martian** [comment]
@unhammer There's also a compiler in this repository.

**Comment by mr-martian** [comment]
A number of pairs have rules in t1x that match an LU and produce a chunk with the same first tag, such as this one from eng-spa:

```
  <rule comment="REGLA: reset variables">
      <pattern>
	<pattern-item n="coma"/>
      </pattern>
      <action>
<!--	<let>
	  <var n="nombre"/>
	  <lit-tag v="sg"/>
	</let>
	<let>
	  <var n="genere"/>
	  <lit-tag v="m"/>
	</let> -->
        <let>
	  <var n="EOS"/>
	  <lit v="false"/>
	</let>
	<out>
	  <chunk name="coma">
	    <tags>
	      <tag><lit-tag v="cm"/></tag>
	    </tags>
	    <lu>
	      <clip pos="1" side="tl" part="whole"/>
	    </lu>
	  </chunk>
	</out>
      </action>
  </rule>
```

Currently, when I compile this, it will apply in the t1x phase and turn `^,<cm>/,<cm>$` into `^coma<cm>{^,<cm>$}$`, as expected. Unfortunately, since it matches `^*<cm>$`, it will apply again in t2x. Since it's being compiled as a t1x rule, it will only clip the surface and will produce `^coma<cm>{^coma<cm>$}$` rather than `^coma<cm>{^coma<cm>{^,<cm>$}$}$`.

That discarding is probably resolvable, but I don't think I can automatically resolve the issue of rules that match their own output.

**Comment by mr-martian** [comment]
Based on tests using eng-deu, `rtx-proc -t` could be used as a drop-in replacement for `apertium-transfer`, `apertium-interchunk`, and `apertium-postchunk`.

However, this would affect a relatively small number of pairs and speed and accuracy would both be mostly unchanged.

Also, `rtx-proc` currently only frees memory when flushing the output stream and `rtx-proc -t` doesn't flush so it runs out of memory and crashes somewhere in the neighborhood of a megabyte of text.
