### ISSUE TITLE
Should deleting a tag be explicit?

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-recursive#54]
A possible improvement to the formalism would be that tags should have to be deleted with `<let>...<lit v=""/></let>`. Assigning an empty clip to a tag using e.g. `<let><clip pos="1" part="a_gen"/><clip pos="2" part="a_gen"/>` should not set the `a_gen` of 1 to '' if the `a_gen` of 2 does not match.

**Comment by ftyers** [comment]
This might be related to #53.

**Comment by mr-martian** [comment]
So you want `<let><clip><clip></let>` to check whether the second clip is empty and do nothing if so?

**Comment by ftyers** [comment]
I think it might be an improvement, but I'm not sure. I'm not sure if there are any genuine times when double clip should result in a deletion. Can you think of any?
