### ISSUE TITLE
Discard More Branches

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium-recursive#6]
GLR mode is currently somewhat slow. The best option for speeding it up is probably to find some way of discarding paths early, rather than holding on to all of them until completion or a parse error.

**Comment by mlforcada** [comment]
Whenever a certain word span is covered exactly by two parse subtrees, 
you could use a criterion (number of nodes, sum of weights, etc.) to 
discard one of them. This involves checking the top of all active 
"stacks". Also, stack items should explicitly carry an indication of the 
span they cover (or at least the word in which they started).

El 5/7/19 a les 22:29, mr-martian ha escrit:
> The best option for speeding it up is probably to find some way of 
> discarding paths early,

-- 
Mikel L. Forcada  http://www.dlsi.ua.es/~mlf/
Departament de Llenguatges i Sistemes Informàtics
Universitat d'Alacant
E-03690 Sant Vicent del Raspeig
Spain
Office: +34 96 590 9776

**Comment by mr-martian** [comment]
Branches of the stack now track how many words the top partial parse covers.

As a first attempt, I checked for branches where this last segment is the same length and discarded lower weighted ones. The result was a roughly 4x speedup. The runtime on my test corpus is 3.5s, which is only a little slower chunker/interchunk (acknowledging the two rulesets are not totally comparable).

**Comment by mr-martian** [comment]
At @mlforcada's suggestion, I implemented rudimentary lookahead.

Now for every instance of a rule matching `x y` and a rule matching `x y z`, the end of the path for the `x y` rule in the transducer has a transition by `<LOOK:AHEAD>` followed by the pattern of `First(z)`. If this pattern does not match the next LU in the input stream, then the parser will only reduce and will not create a shift branch.

This change does not appear to have caused any regressions and sped up the parser by a factor of roughly 15.

For a set of 31 rules on an input of about 75k LUs, the running time on my computer is roughly 1.3 seconds. eng-spa chunker/interchunk/postchunk on the same input takes 2.3s in sequence or 1.1s in parallel. A full recursive ruleset for eng-spa would thus probably have a comparable running time to the current non-recursive one.
